import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "../globals.css";
import ClientProviders from "./providers/ClientProviders";

const inter = Inter({ subsets: ["latin"] });
const RobotoRegular = Roboto({
  subsets: ["latin"],
  variable: "--font-Roboto-extra-bold",
  display: "swap",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Point Of Sale",
  description: "Generated by Prashant Agarwal",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={RobotoRegular.className}>
        {/* Wrap children with the Client Providers */}
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
